FROM nginx:stable

RUN rm /etc/nginx/conf.d/default.conf
COPY nginxcertbot.conf /etc/nginx/nginx.conf
RUN mkdir -p /var/www/certbot

RUN touch /var/log/nginx/access.log
RUN chown nginx:nginx /var/log/nginx/access.log

CMD ["nginx", "-g", "daemon off;"]