version: "0.0.1"
services:
  nginx_app: 
    container_name: nginx_app
    build: 
      context: .
      dockerfile: Dockerfile.nginxapp
    restart: unless-stopped
    networks:
      - nginx_net
    ports:
      - "80:80"
    volumes:
      - ./logs/nginx:/var/log/nginx
  app:
    image: freeko/bank_app:hw_26
    container_name: bank_app
    restart: unless-stopped
    networks:
      - nginx_net
    ports:
      - "5000:5000" 
      
networks:
  nginx_net:
    name: nginx_net
