version: "0.0.1"
services:

  nginx: 
    container_name: nginx
    build: 
      context: .
      dockerfile: Dockerfile.nginx
    depends_on:
      - app
    restart: unless-stopped
    networks:
      - nginx_net
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/letsencrypt/:ro
    
  app:
    image: freeko/bank_app:hw_26
    container_name: bank_app
    restart: unless-stopped
    networks:
      - nginx_net
    ports:
      - "5000:5000"  

  certbot:
    image: certbot/certbot:latest
    restart: unless-stopped
    depends_on:
      - nginx
    networks:
      - nginx_net
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

networks:
  nginx_net:
    name: nginx_net