version: "0.0.1"
services:
  app:
    image: freeko/bank_app:hw_26
    container_name: bank_app
    ports:
      - "5000:5000"
  

  nginx: 
    container_name: nginx
    build: 
      context: .
      dockerfile: Dockerfile.nginx
    depends_on:
      - app
    ports:
      - "80:80"
      - "443:443"
    volumes:
    - ./certs:/etc/letsencrypt

  certbot:
    image: certbot/certbot
    command: 
      - certonly --webroot --webroot-path=/var/www/certbot --email baturevichdmitry@gmail.com --agree-tos --no-eff-email --staging -d bdi.bank.smodata.net
    depends_on:
      - nginx
    volumes:
      - ./certs:/etc/letsencrypt  
    environment:
      - NGINX_CONTAINER_NAME=nginx