FROM nginx:stable

RUN rm /etc/nginx/conf.d/default.conf
COPY nginx.conf /etc/nginx/nginx.conf

RUN touch /var/log/nginx/access.log
RUN chown nginx:nginx /var/log/nginx/access.log

CMD ["nginx", "-g", "daemon off;"]