- name: Install Pythonh 3.11 
  block:
    - name: Clone the Pyenv repository
      git:
        repo: https://github.com/pyenv/pyenv.git
        dest: /home/{{app_user}}/.pyenv
        update: yes
      become_user: "{{app_user}}"

    - name: Добавление перемнных в .basrc
      blockinfile:
        path: /home/{{app_user}}/.bashrc
        block: |
          export PYENV_ROOT="$HOME/.pyenv"
          export PATH="$PYENV_ROOT/bin:$PATH"
          eval "$(pyenv init --path)"
        state: present
    
    - name: Установка зависимостей для создания виртуального окружения
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - python3-pip
        - build-essential
        - libssl-dev
        - libffi-dev
        - python3-dev
        - python3
        - python3-venv

    - name: Установка Python 3.11.3 с помощью pyenv
      shell:  ~/.pyenv/bin/pyenv versions | grep -q 3.11.3 || /home/{{app_user}}/.pyenv/bin/pyenv install 3.11.3
      args:
        executable: /bin/bash
      changed_when: false
      become_user: "{{app_user}}"

    - name: Install Poetry 
      pip:
        name: poetry
        state: present

    - name: Install python
      shell: /home/{{app_user}}/.pyenv/bin/pyenv global 3.11.3
      args:
        executable: /bin/bash
      become_user: "{{app_user}}"
    
    - name: Выполнение команды с переменными окружения
      shell: |
        export PYENV_ROOT="$HOME/.pyenv"
        export PATH="$PYENV_ROOT/bin:$PATH"
        eval "$(pyenv init --path)"
        env
        cd {{project_dir}}
        poetry install   
      args:
        executable: /bin/bash
      become_user: "{{app_user}}"

    