replicaCount: 2
image:
  repository: freeko/bank_app
  pullPolicy: IfNotPresent
  tag: 33404fafe92d07d5db0a26317da64bd359f202c3
imagePullSecrets: []
nameOverride: ''
fullnameOverride: ''
serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: bank-serviceaccount
podAnnotations: {}
podLabels: {}
podSecurityContext: {}
securityContext: {}
service:
  type: ClusterIP
  port: 80
  protocol: TCP
  targetport: 80
ingress:
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/use-regex: 'true'
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/service-upstream: 'true'
    cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts:
    host: api.bpzb.smodata.net
    http:
      paths:
        path: /bank(.*)
        pathType: ImplementationSpecific
      port: 80
  tls:
    secretName: bpzb
resources: {}
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
volumes: []
volumeMounts:
  name: nginx-config
  mountPath: /etc/nginx
nodeSelector: {}
tolerations: []
affinity: {}
deployment:
  strategy:
    type: RollingUpdate
    maxSurge: 2
  template:
    specNginx:
      name: nginx
      image: nginx:1.25.2
      ports:
        containerPort: 80
        name: http
        protocol: TCP
  env:
    name_base: PG_DATABASE
    name_base_value: bpzb
    username_db: PG_USER
    usernameKeyRef:
      username: PG_USER
      password: PG_PASSWORD
      name: bpzb-db-creds
    password: PG_PASSWORD
    hostname: PG_HOST
    hostname_value: omegabank-rds-tf.cearikylb8tb.eu-west-1.rds.amazonaws.com
    port_name: PG_PORT
    port_value: '5432'
  volume_configMap: nginx-config
labels:
  app: bank
  bank: bpzb
  env: prd
