- name: Copy app.service.j2 file
  template:
    src: app.service.j2
    dest: /etc/systemd/system/{{service_name}}.service
    owner: root
    group: root
    mode: '0644'

- name: Configure systemd service
  systemd:
    name: "{{service_name}}.service"
    enabled: yes
    state: started
    daemon_reload: yes

- name: Start systemd service
  systemd:
    name: "{{service_name}}.service"
    state: started