- name: Install Git
  block:
    - name: Add Git PPA repository
      apt_repository:
        repo: ppa:git-core/ppa
        state: present
        update_cache: yes

    - name: Update apt package cache
      apt:
        update_cache: yes

    - name: Install Git package
      apt:
        name: "{{git_vers}}"
        state: present
    
    - name: Clone repository
      git:
        repo: "{{git_repo}}"
        dest: "{{project_dir}}"
        version: "{{git_branch}}"
        force: yes
      become_user: "{{git_user}}"