apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: bpzb-bank
  finalizers:
#    - resources-finalizer.argocd.argoproj.io
spec:
  project: bpzb
  source:
    repoURL: 'https://github.com/Freek0/dos14-baturevich_dmitry-git-flow.git'
    path: k8s/bank
    targetRevision: feature-k8s
    helm:
      valueFiles:
        - values-prd.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: bpzb
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
