- name: Install Docker
  block:
  - name: Add Docker repository key
    apt_key:
      url: "{{docker_repo_key}}"
      state: present

  - name: Add Docker repository
    apt_repository:
      repo: "{{docker_repo}}"
      state: present
      filename: docker
      update_cache: yes
  
  - name: Install Docker
    apt:
      name:
        - docker-ce
        - docker-ce-cli
        - containerd.io
      state: present

  - name: Install Docker Compose
    get_url: 
      url : "{{docker_compose_url}}"
      dest: /usr/local/bin/docker-compose
      mode: 'u+x,g+x'
