- name: Docker compose
  block:
    - name: Замена пути в docker-compose.yml
      replace:
        path: "{{project_dir}}/docker-compose.yml"
        regexp: '^(\s+build:)\s+.+$'  
        replace: '\1 {{project_dir}}'
        
    - name: docker compose up
      shell: docker compose -f {{project_dir}}/docker-compose.yml up -d
      

    # - name: Build container (docker-compose)
    #   community.docker.docker_compose:
    #     project_src: "{{project_dir}}"
    #   become: true
  
  # - name: Pull an image
  #   community.docker.docker_image:
  #     name: freeko/bank_app:HW_25
  #     source: pull

  # - name: Create docker conatiner 
  #   community.docker.docker_container:
  #     name: bank_app
  #     image: freeko/bank_app:HW_25
  #     user: appuser
  #     state: started
  #     recreate: true
  #     exposed_ports:
  #       - 5000:5000
